### ISSUE TITLE
keys.sql bevat reference naar onbestaande tabel

### ISSUE THREAD

**Issue by Mmaarten23** [eliavw/db-2021#1]
![image](https://user-images.githubusercontent.com/55060393/112845138-d35c2600-90a4-11eb-88ac-4dee205fffff.png)
Deze error wordt weergegeven bij het importeren van de key.sql file (na het inmporteren van de database)
Query: ALTER TABLE AllstarFull ADD CONSTRAINT PRIMARY KEY (playerID,gameID)

**Comment by eliavw** [comment]
lees aub richtlijnen op toledo omtrent vragen/opmerkingen
